before:
  hooks:
    - go mod tidy
builds:
  - id: kubectl-print-env
    main: ./cmd/kubectl-print-env
    binary: kubectl-print-env
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s
      - -X kubectl-print-env/internal/version.version={{ trimprefix .Version "v" }}
      - -X kubectl-print-env/internal/version.gitCommit={{ .Commit }}
    env:
      - CGO_ENABLE=0
archives:
  - files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Version }}-next-{{ .ShortCommit }}"
nfpms:
  - homepage: https://github.com/pedrobarco/kubectl-print-env
    description: kubectl-print-env is a kubectl plugin that builds config files from k8s environments
    maintainer: Pedro Barco <pedro.barco@tecnico.ulisboa.pt>
    license: MIT
    formats:
      - apk
      - deb
      - rpm
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
